### ISSUE TITLE
Code review Devgym 🎉 

### ISSUE THREAD

**Issue by filhodanuvem** [rafaelmgr12/moviego-cli#1]
Primeiramente parabéns por ter aceito esse desafio @rafaelmgr12 . 
Esse desafio tem alguns pontos principais que o torna complexo: 

### leitura do arquivo 
O arquivo contém 27k filmes, mas precisamos imaginas um arquivo muito maior. Existem formas diferentes de ler o arquivo,na sua implementação você acaba [lendo o arquivo inteiro](https://github.com/rafaelmgr12/moviego-cli/blob/main/utils/ManagerFiles.go#L19) e colocando ele todo na memória de uma vez, dependendo do tamanho do arquivo e do ambiente que rodarmos o programa, podemos não ter memória RAM suficiente. Eu ainda não testei essa [opção do docker-compose](https://stackoverflow.com/questions/42345235/how-to-specify-memory-cpu-limit-in-docker-compose-version-3) mas acho que daria pra definir um limite de memória pra simular um caso de erro. Se você se interessar por esse tópico pode dar uma lida [nesse post](https://www.golinuxcloud.com/golang-read-a-file-methods/#3_Read_file_line_by_line_in_GoLang) que mostra diferentes formas de ler um arquivo grande, a ideia é ir lendo aos poucos, por exemplo, colocar X linhas  a memória, salvar os filmes no banco e depois ler as próprias X linhas. 

### Inserindo no banco em batch 
Vi que você usou o GORM mas chamou o método [create para cada filme](https://github.com/rafaelmgr12/moviego-cli/blob/main/main.go#L49), isso quer dizer que você vai fazer 27k escritas em disco, bem exaustivo pro banco. Seria melhor agrupar vários filmes num batch e inseri-los todos de uma vez.  [O GORM aceita um array](https://gorm.io/docs/create.html#Batch-Insert) e provavelmente vai montar uma insert query com todos os filmes do array.  O postgres tem umas limitações no número de linhas que podem ser inseridas de uma vez, então é preciso testar isso. 

Fiquei curioso pra saber se você experienciou algum problema que foi resolvido com o[ mutex aqui](https://github.com/rafaelmgr12/moviego-cli/blob/main/main.go#L47). A minha primeira impressão foi, se você tem várias goroutines tentando escrever ao mesmo tempo, mas tem um mutex, então você esta fazendo todas as goroutines esperarem pra outra routine liberar o lock. Eu acho que o próprio banco de dados consegue lidar com isso. 

O código ficou bem legal com o uso de waitGroup and go routines, só gostaria de pedir atenção que o número de go routines é exatamente o número de linhas do do arquivo. Isso me faz pensar algumas coisas: Cada goroutine tem uma memória (pequena) alocada para ela, então se o arquivo for muito grande, você pode esbarrar em problemas por ter muitas goroutines. Usar buffered channels pode ajudar. Além disso também me pergunto se a solução não esbarra em algum problema de número de conexões abertas. 

 
### Parser
Existem alguns filmes com varios parenteses no titulo, por exemplo o filme 1340 `Bride of Frankenstein, The (Bride of Frankenstein) (1935)` eu acho que nesse caso você vai acabar usando `Bride of Frankenstein) (1935)` como year, se for o caso é só um detalhe. 

Em geral, de novo, parabéns pela solução, dá gosto de ver como você tem carinho pelos projetos, com um readme muito foda, tratando o projeto como um grande projeto open source. Saiba que essa forma de organização tem seu valor no mercado em processos seletivos reais.

**Comment by rafaelmgr12** [comment]
Olá, @filhodanuvem. Tudo bem? Fiquei muito feliz com seu review, e trabalharei nas sugestões que você me trouxe.  
Agradeço muito o seu tempo gasto.
